# Generated by Django 3.2.6 on 2022-01-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0003_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='money',
            field=models.IntegerField(default=76000),
        ),
    ]
